<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC335498" name="com.pearson.tests.CSG641DefaultContentSearchBeh" tests="1" failures="0" timestamp="8 Aug 2016 07:06:20 GMT" time="0.447" errors="1">
  <testcase name="SearchContent_with_valid_IndexId_POST" time="0.447" classname="com.pearson.tests.CSG641DefaultContentSearchBeh">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:83)
	at com.pearson.tests.CSG641DefaultContentSearchBeh.SearchContent_with_valid_IndexId_POST(CSG641DefaultContentSearchBeh.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.NullPointerException
	at com.pearson.regression.utilityHelpers.ExcelRead.getHeader(ExcelRead.java:55)
	at com.pearson.regression.utilityHelpers.ExcelRead.getData(ExcelRead.java:34)
	at com.pearson.tests.CSG641DefaultContentSearchBeh.SearchContent_with_valid_IndexId_POST(CSG641DefaultContentSearchBeh.java:23)
	... 24 more
]]>
    </error>
  </testcase> <!-- SearchContent_with_valid_IndexId_POST -->
</testsuite> <!-- com.pearson.tests.CSG641DefaultContentSearchBeh -->
